spring:
  application:
    name: Pokémon Trade Card Collection
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Admin@123
    url: jdbc:postgresql://localhost:5432/pokemon-tcg
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
  sql:
    init:
      platform: postgres
      mode: always
      continue-on-error: true
server:
  servlet:
    context-path: /pokemon-tcg/v1
  port: '8080'

